### ISSUE TITLE
Minimum OS requirement is Ubuntu specific

### ISSUE THREAD

**Issue by pixdrift** [Sysinternals/ProcMon-for-Linux#8] opened 2020-07-17 07:45 UTC
Hi,

From the README.md:

> 
>  Minimum OS:
>  Ubuntu 18.04 lts

Is there something specific to Ubuntu 18.04 LTS that makes Ubuntu the Minimum OS version? Is there a kernel version, feature or library requirement that can be defined here instead?

**Comment by stemid** [comment] 2020-07-17 08:05
I tried building it on Fedora by installing the following packages;

    sudo dnf install bison '@Development tools' flex libedit-devel llvm6.0-devel llvm6.0-libs \
      clang-devel elfutils-libelf-devel zlib-devel llvm6.0-static bcc

But when running cmake I just get this issue.

```
-- Found LLVM: /usr/lib64/llvm6.0/include 6.0.1
CMake Error at build/_deps/bcc-src/CMakeLists.txt:58 (message):
  Unable to find clang libraries
```

I tried pointing to the LLVM dirs with `-DCMAKE_PREFIX_PATH=/usr/lib64` and `-DLLVM_LIBRARY_DIRS=/usr/lib64/llvm6.0/lib` but no joy. Anyone got any idea how to compile this?

I can't find clang6.0 on Fedora 32, package was orphaned a while back.

**Comment by Worty** [comment] 2020-07-17 11:06
Arch and Fedora is using clang 10 which cant build bcc 0.10 (https://github.com/iovisor/bcc/commit/1599c2ef8206988d5d)

**Comment by stemid** [comment] 2020-07-17 12:33
I came a bit further towards running it on Fedora with this Dockerfile but it's still generating a lot of errors and the curses UI is empty of any data so it doesn't seem to work.

Maybe it's helpful to some Fedora user.

```
FROM ubuntu:18.04

VOLUME .:/source
COPY install_bcc.sh /source/install_bcc.sh

RUN apt update
RUN apt install apt-transport-https ca-certificates gnupg software-properties-common wget -y
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt install kitware-archive-keyring -y
RUN apt install -y cmake libsqlite3-dev bison build-essential flex git libedit-dev libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev iperf netperf arping
RUN bash /source/install_bcc.sh
ENTRYPOINT /bin/bash
```

install_bcc.sh is simply;

```#!/usr/bin/env bash

cd /source
git clone --branch tag_v0.10.0 https://github.com/iovisor/bcc.git
mkdir bcc/build
cd bcc/build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j$(nproc)
make install
```

    $ docker build -t procmon .

I've downgraded my F32 system to cgroupsv1 because I feel that podman isn't ready for daily use yet.

**Comment by MarioHewardt** [comment] 2021-06-21 15:43
Duplicate of #70

**Closed by MarioHewardt** 2021-06-21 15:43 UTC
Labels: Build, Distro, documentation
