### ISSUE TITLE
Segmentation fault after loading procmon Debian 11

### ISSUE THREAD

**Issue by gui28347** [Sysinternals/ProcMon-for-Linux#79] opened 2021-08-25 03:56 UTC
* I was able to build successfully but after executing procmon with no parameters it crash with segmentation fault message

* Warnings during load:
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:69:
include/linux/compiler-clang.h:45:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:69:
include/linux/compiler-clang.h:46:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:69:
include/linux/compiler-clang.h:47:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
3 warnings generated.

Crash:
 
![image](https://user-images.githubusercontent.com/8279438/130723984-1a3eecda-212d-4841-b1b7-e522b0a0118a.png)

**Comment by jahabibi** [comment] 2021-08-25 16:31
Hey @gui28347 sorry to hear that you are having this issue. At this point in time the preview of Procmon for Linux is only supported on Ubuntu due to known issues with one of our dependencies. We are actively working to resolve this moving forward so that we can expand our distro support as we move towards a GA release.

**Comment by jahabibi** [comment] 2021-09-03 23:43
Related issue #70.

**Comment by MarioHewardt** [comment] 2022-05-05 16:20
Duplicate of #70

**Closed by MarioHewardt** 2022-05-05 16:20 UTC
